nome = input("Qual seu nome?")
dia = input("Qual o dia do seu nascimento?")
mes = input("Qual o mês do seu nascimento?")
ano = input("Qual o ano do seu nascimento?")
print(nome, dia, mes, ano)
print("Olá " + nome + ", você nasceu no dia " + dia + " de " + mes + " de " + ano + ". Correto?")